export default {
  Pallete: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  PalleteColors: {
    height: "90%",
  },
  SingleColorPallete: {
    height: "90%",
  },
  BackButton: {
    width: "20%",
    height: "25%",
    backgroundColor:"black",
    height: "50%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-3.5px",
    "& a": {
      width: "100px",
      height: "30px",
      position: "absolute",
      display: "inline-block",
      top: "45%",
      left: "35%",
      // marginLeft: -"50px",
      // marginTop: -"15px",
      textAlign: "center",
      outline: "none",
      fontSize: "1rem",
      lineHeight: "30px",
      color: "white",
      textTransform: "uppercase",
      border: "none",
      textDecoration: "none",
      background: "rgba(255, 255, 255, 0.3)",

    },
  },
};